LxMyblog/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
"""LxMyblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve

from my_users.views import LoginView, RegisterView, LogoutView
from LxMyblog.settings import MEDIA_ROOT
from my_blog.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name="index"),
    url(r'^blog/', include('my_blog.urls', namespace='index')),
    url(r'^users/', include('my_users.urls', namespace='users')),
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    # url(r'static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),


    # 登录
    url(r'^login/', LoginView.as_view(), name='login'),
    # 退出
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    # 注册
    url(r'^register/', RegisterView.as_view(), name='register'),

]

my_blog/urls.py
# !/usr/bin/env python 
# -*- coding:utf-8 -*-
__author__ = '_X.xx_'
__date__ = '2018/6/21 22:10'

from django.conf.urls import url
from .views import AboutView, ArticleView, AddCommentsView, ProjectView, \
    ProjectDetailView, TemplateView

urlpatterns = [
    # 关于我页面
    url(r'^about$', AboutView.as_view(), name='about'),
    # 图片显示页
    url(r'^template$', TemplateView.as_view(), name='template'),
    # 点击阅读全文跳转页面
    url(r'^detail/(?P<article_id>\d+)/$', ArticleView.as_view(), name='detail'),
    # 添加文章评论
    url(r'^add_comment/(?P<article_id>\d+)$', AddCommentsView.as_view(),
        name="add_comment"),
    # 项目简介
    url(r'^project$', ProjectView.as_view(), name='project'),
    # 点击阅读全文跳转页面
    url(r'^project_detail/(?P<project_id>\d+)/$', ProjectDetailView.as_view(),
        name='project_detail'),

]

my_users/urls.py
# !/usr/bin/env python 
# -*- coding:utf-8 -*-
__author__ = '_X.xx_'
__date__ = '2018/6/21 23:07'

from django.conf.urls import url
from .views import UserInfoView, UploadImageView, UpdatePwdView, UserinfoView

urlpatterns = [
    # 用户个人资料页
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),
    # 用户修改头像
    url(r'^image/up_load$', UploadImageView.as_view(), name='up_load'),
    # 用户修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    # 用户修改资料
    url(r'^update/user_info/$', UserinfoView.as_view(), name='user_info'),
]

my_blog/models.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from datetime import datetime
from my_users.models import UserProfile


class IndexArticle(models.Model):
    """
        首页文章模型
    """
    name = models.ForeignKey(UserProfile, verbose_name=u'用户名')
    title = models.CharField(max_length=20, verbose_name=u'文章标题')
    content = models.TextField(verbose_name=u'文章内容')
    image = models.ImageField(upload_to='article/%Y/%m', max_length=100,
                              verbose_name=u'文章图片')
    url = models.URLField(max_length=200, verbose_name=u'访问地址')
    author = models.CharField(max_length=20, verbose_name=u'文章作者')
    classify = models.CharField(max_length=10, verbose_name=u'文章分类', choices=(
        ('rj', u'日记'), ('bk', u'个人播客'), ('xd', u'心得笔记')), default='bk')
    click_num = models.IntegerField(default=0, verbose_name=u'浏览量')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'首页文章'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.title


class ArticleComments(models.Model):
    """
        文章评论
    """

    user = models.ForeignKey(UserProfile, verbose_name=u'用户')
    article = models.ForeignKey(IndexArticle, verbose_name=u'文章')
    comments = models.CharField(max_length=200, verbose_name=u'评论')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'文章评论'
        verbose_name_plural = verbose_name


class ReadArticle(models.Model):
    """
        阅读书籍
    """
    title = models.CharField(max_length=20, verbose_name=u'文章标题')
    content = models.TextField(verbose_name=u'文章内容')
    image = models.ImageField(upload_to='article/%Y/%m', max_length=100,
                              verbose_name=u'文章图片')
    url = models.URLField(max_length=200, verbose_name=u'访问地址')
    author = models.CharField(max_length=20, verbose_name=u'文章作者')
    classify = models.CharField(max_length=10, verbose_name=u'文章分类', choices=(
        ('rj', u'日记'), ('xs', u'欣赏'), ('cx', u'程序人生'), ('jd', u'经典语录'),),
                                default='xs')
    click_num = models.IntegerField(default=0, verbose_name=u'浏览量')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'阅读书籍'
        verbose_name_plural = verbose_name

    def __unicode__(self):
        return self.title

my_blog/views.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.views.generic import View
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from .models import IndexArticle, ArticleComments, ReadArticle
from django.http import HttpResponse
from utils.mixin_utils import LoginRequiredMixin
from my_users.models import UserProfile


class IndexView(View):
    """
        首页文章
    """

    def get(self, request):
        # 取出首页文章
        articles_index = IndexArticle.objects.all()
        # 根据添加时间排序
        article_news = IndexArticle.objects.all().order_by('add_time')[:10]
        # 根据点击量排序
        article_clicks = IndexArticle.objects.all().order_by('-click_num')[:10]
        # 分类显示文章
        bj_articles = request.GET.get('ct', '')
        if bj_articles:
            articles_index = articles_index.filter(classify=bj_articles)
        # 对文章进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(articles_index, 2, request=request)
        articles = p.page(page)

        # 对文章数统计
        article_num = articles_index.count()
        return render(request, 'my_blog/index.html', {
            'articles_index': articles,
            'article_news': article_news,
            'article_clicks': article_clicks,
            'bj_articles': bj_articles,
            'article_num': article_num
        })


class AboutView(View):
    """
        关于我
    """

    def get(self, request):
        return render(request, 'my_blog/about.html')


class ProjectView(View):
    """
        项目简介
    """

    def get(self, request):
        all_read = ReadArticle.objects.all()
        click_read = ReadArticle.objects.all().order_by('-click_num')
        # 分类显示文章
        fl_articles = request.GET.get('ct', '')
        if fl_articles:
            all_read = all_read.filter(classify=fl_articles)
        # 对文章进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_read, 3, request=request)
        reads = p.page(page)
        return render(request, 'my_blog/newlist.html', {
            'all_read': reads,
            'classify': fl_articles,
            'click_read': click_read

        })


class TemplateView(View):
    """
        显示页
    """
    def get(self, request):
        return render(request, 'my_blog/share.html')


class ProjectDetailView(View):
    """
        详情页
    """
    def get(self, request, project_id):
        all_reads = ReadArticle.objects.get(id=int(project_id))
        all_reads.click_num += 1
        all_reads.save()
        return render(request, 'my_blog/project.html', {
            'all_reads': all_reads
        })


class ArticleView(View):
    """
        浏览量点击自增
    """

    def get(self, request, article_id):
        articles = IndexArticle.objects.get(id=int(article_id))
        # 点击量自增
        articles.click_num += 1
        articles.save()
        all_comments = ArticleComments.objects.filter(article_id=articles).order_by('-add_time')
        # 根据评论时间排序
        new_comments = ArticleComments.objects.filter(
            article_id=articles).order_by('-add_time')[:6]
        # 取出访客用户
        all_user = UserProfile.objects.all()
        # 对文章进行分页
        try:
            page = request.GET.get('page', 1)
        except PageNotAnInteger:
            page = 1
        p = Paginator(all_comments, 3, request=request)
        comment_page = p.page(page)
        return render(request, 'my_blog/detail.html', {
            'articles': articles,
            'all_comments': comment_page,
            'new_comments': new_comments,
            'all_user': all_user
        })


class AddCommentsView(LoginRequiredMixin, View):
    """
        添加文章评论
    """

    def post(self, request, article_id):
        if not request.user.is_authenticated():
            # 判断用户登录状态
            return HttpResponse('{"status":"fail", "msg":"用户未登录"}',
                                content_type='application/json')

        comments = request.POST.get('comments', '')
        if comments:
            article_comments = ArticleComments()
            article = IndexArticle.objects.get(id=int(article_id))
            article_comments.article = article
            article_comments.comments = comments
            article_comments.user = request.user
            article_comments.save()
            return HttpResponse('{"status":"success", "msg":"添加成功"}',
                                content_type='application/json')
        else:
            return HttpResponse('{"status":"fail", "msg":"添加失败"}',
                                content_type='application/json')

templates/my_blog/about.html
{% extends 'my_blog/index.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link href="{% static 'my_blog/css/about.css' %}" rel="stylesheet">
    <link href="{% static 'my_blog/css/index.css' %}" rel="stylesheet">

{% endblock %}
{% block title %}
    X.xx关于我
{% endblock %}
{% block coutent %}
     <article>
     {% block bread %}
    <h3 class="about_h">您现在的位置是：<a href="/">首页</a>><a href="{% url 'index:about' %}">关于我</a></h3>
     {% endblock %}
    <div class="about">
      <h2>Just about me</h2>
      <ul>
          <p>
              X.xx 一个编程笨鸟
          </p>
          <p>
                年轻，就该奋斗

年轻的我们就像还是漂泊的小船，虽然有时候找不到最终的方向，但我们务必得往前行，努力找到停泊的彼岸。

年轻一次不容易，有一首歌说的好，“再不疯狂我们就老了”，年轻就该疯狂，但更就应奋斗才行。

年轻的我们能够犯错，年轻的我们能够错过，年轻的我们还输得起。没有比脚更长的路，没有比年轻更好的青春，所以走好青春的每一步。

有努力就有期望，年轻的心有的是激情、力量、勇气。我们能够大胆的做自己，做那个心中最“疯狂”，最真实的自己。

年轻就该经历酸甜苦辣，年轻就该流泪呐喊，是我们的就该去追逐，不是我们的我们依然能够去争取，因为我们还年轻，趁青春还在，抓住青春的尾巴，在人生的战场上留下一笔属于自己的辉煌战绩！
          </p>
          <p>
              送给所有奋斗中的我们

人生，就是一场自己与自己的较量：

让用心打败消极，让快乐打败忧郁，让勤奋打败懒惰，让坚强打败脆弱。

在每一个充满期望的清晨，告诉自己：努力，就总能遇见更好的自己。

每一天给自己一个期望，不为明天烦恼，不为昨日叹息。

如果只是等待，惟一会发生的事，就是你变老了。

没有永久的失败，只是暂时没有成功。

生活不会更容易，但你能够因此更强大。

努力做好自己，不管是被命运赏识，还是被宿命淹没。

当梦想还在，就不要放弃飞翔和追逐。

若不给自己设限，就没有能限制你挥洒的藩篱。

感觉走起来个性艰难就对了，说明你正在走上坡路。

不要躲避风雨，风雨之后就是彩虹。
          </p>
          <p>
              奋斗，与梦想同在
          </p>
      </ul>
      <h2>About my blog</h2>

    </div>
  </article>
{% endblock %}

{% block news %}
{% endblock %}

templates/my_blog/base_blog.html
{% load staticfiles %}
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>{% block title %}X.xx播客首页{% endblock %}</title>
<meta name="keywords" content="小熙个人博客" />
<meta name="description" content="小熙个人博客，神秘、俏皮。" />
<link href="{% static 'my_blog/css/base.css' %}" rel="stylesheet">
<link href="{% static 'my_blog/css/media.css' %}" rel="stylesheet">
<link href="{% static 'my_blog/css/style.css' %}" rel="stylesheet">
{% block custom_css %}
{% endblock %}
{% block custom_js %}
{% endblock %}
<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0">
<!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<div class="ibody">
  <header>
    <h1>小熙_Strive</h1>
    <h2>平凡生活，英雄梦想。做努力爬的蜗牛或坚持飞的笨鸟。总有一天，你会站在最亮的地方，活成你自己曾经渴望的模样。..</h2>

    <div class="logo"><a href="/"></a></div>
    {% block nav %}
        {% if request.user.is_authenticated %}
            <nav id="topnav"><a href="{% url 'index' %}">首页</a><a href="{% url 'index:about' %}">关于我</a><a href="{% url 'index:project' %}">阅读人生</a><a href="{% url 'index:template' %}">个人作品</a><a href="{% url 'logout' %}">退出</a></nav>
           {% else %}
            <nav id="topnav"><a href="{% url 'index' %}">首页</a><a href="{% url 'index:about' %}">关于我</a><a href="{% url 'index:project' %}">阅读人生</a><a href="{% url 'index:template' %}">个人作品</a><a href="{% url 'login' %}">登录</a><a href="{% url 'register' %}">注册</a></nav>
        {% endif %}
    {% endblock %}

  </header>
    {% block coutent %}
            {% block bread %}
            {% endblock %}
    {% endblock %}
{% block right_coutent %}

{% endblock %}
  <script src="{% static 'my_blog/js/silder.js' %}"></script>
  <div class="clear"></div>
</div>
</body>
</html>

templates/my_blog/detail.html
{% extends 'my_blog/index.html' %}
{% load staticfiles %}
{% block custom_css %}

    <link href="{% static 'my_blog/css/about.css' %}" rel="stylesheet">
    <link href="{% static 'my_blog/css/index.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/learn-less.css' %}"/>
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/course-comment.css' %}"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
    <link rel="stylesheet" type="text/css"
          href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/mooc.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'my_blog/css/style.css' %}"/>
    <style>
        .test {width: 30px; height: 30px; float: left; margin: 20px 10px}
        .test img {width: 40px; height: 40px; }
    </style>
{% endblock %}


{% block nav %}

    <nav id="topnav"><a href="{% url 'index' %}">回到首页</a> </nav>
{% endblock %}
{% block coutent %}
    <article>
        {% block bread %}
            <h3 class="about_h">您现在的位置是：<a href="{% url 'index' %}">首页</a>><a href="#">文章详情</a></h3>
        {% endblock %}
        <div class="about">
            <h2>{{ articles.title }}</h2>
            <p>{{ articles.content }}</p>
            <div id="main">
            <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">

                        <li><span
                                style="color: #e41635; font-size:20px ">评论</span>
                        </li>
                    </ul>
                </div>
                <!--发布评论-->

                <div id="js-pub-container"
                     class="issques clearfix js-form">
                    <form method="post" action="{% url 'index:add_comment' articles.id %}">
                        <div class="wgt-ipt-wrap pub-editor-wrap " id="js-pl-input-fake">
                            <textarea id="js-pl-textarea" name="comments" placeholder="表扬、鼓励……想说啥就说啥！"></textarea>
                        </div>
                        <input type="submit" id="submit"  class="pub-btn" data-cid="452"  value="发表评论">
                        <p class="global-errortip js-global-error"></p>
                        {% csrf_token %}
                    </form>
                </div>
                <div id="course_note">
                <ul class="mod-post" id="comment-list">
                {% for all_comment in all_comments.object_list %}
                    <li class="post-row">
                    <div class="media">
                        <span target="_blank"><img  src='{{ MEDIA_URL }}{{ all_comment.user.image }}'width='40'  height='40'/></span>
                    </div>
                    <div class="bd">
                    <div class="tit">
                    <span target="_blank"
                      {% if all_comment.user.nick_name == '小熙' %}style="color: #e41635; font-size: 20px; font-weight: bold; font-family: 楷体; font-style:italic"{% endif %}>{{ all_comment.user.nick_name }}</span>
                    </div>
                    <p class="cnt"
                       {% if all_comment.user.username == 'lianxi' %}style="color: #e41635; font-size: 15px; font-weight: bold;  font-style:italic"{% endif %}>{{ all_comment.comments }}</p>
                    <div class="footer clearfix">
                        <span title="创建时间"  class="l timeago">时间：{{ all_comment.add_time }}</span>
                    </div>
                    </div>
                    </li>
                {% endfor %}
                </ul>
                </div>
            <div class="page">

                {% if all_comments.has_previous %}
                    <a href="?{{ all_comments.previous_page_number.querystring }}">上</a>
                {% endif %}

                {% for page in all_comments.pages %}
                    {% if page %}
                        {% ifequal page all_comments.number %}
                            <a href="?{{ page.querystring }}">{{ page }}</a>
                        {% else %}
                           <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                        {% endifequal %}

                    {% endif %}
                {% endfor %}
                {% if all_comments.has_next %}
                    <a href="?{{ all_comments.next_page_number.querystring }}">下</a>
                {% endif %}
            </div>
            </div>
            </div>

            <div class="clear"></div>
            </div>
        </div>

    </article>

{% endblock %}

{% block news %}
    <div class="ph_news">
       <h2>
        <p>最新评论</p>
      </h2>
      <ul class="pl_n">
          {% for new_comment in new_comments %}
            <dl>
          <dt><img src="{{ MEDIA_URL }}{{ new_comment.user.image }}"> </dt>

          <dd>{{ new_comment.user.nick_name }}
            <time>{{ new_comment.add_time|timesince }} 前</time>
          </dd>

          <dd><a href="/">{{ new_comment.comments }}</a></dd>
        </dl>
          {% endfor %}
      </ul>
      <h2>
        <p>最近访客</p>
       </h2>
        {% for user_img in all_user %}
         {% if user_img.username != 'lianxi' %}
        <div class="test">

                <img src="{{ MEDIA_URL }}{{ user_img.image }}">

        </div>
         {% endif %}
        {% endfor %}
    </div>

{% endblock %}

templates/my_blog/index.html
{% extends 'my_blog/base_blog.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link href="{% static 'my_blog/css/index.css' %}" rel="stylesheet">
    <link href="{% static 'my_blog/css/style.css' %}" rel="stylesheet">

{% endblock %}

{% block coutent %}
    <article>
    <div class="banner">
      <ul class="texts">
        <p style="color:#e41635; font-weight: bold">人总爱跟别人比较，看看有谁比自己好，又有谁比不上自己。 </p>
        <p style="color: #ffffff; font-weight: bold">而其实，为你的烦恼和忧伤垫底的，从来不是别人的不幸和痛苦，而是你自己的态度。</p>
      </ul>
    </div>
    <div class="bloglist">

      <h2>
        {#根据标签分类#}
        <p><span><a href="?ct=">全部|</a></span><a href="?ct=bk">播客|</a><a href="?ct=rj">日记|</a><a href="?ct=xd">心得</a> </p>
      </h2>

        <h2>
        {#根据标签分类#}
         <p><span>共  </span>{{ article_num }}  <span>篇文章</span> </p>
        </h2>
        {% for article_index in articles_index.object_list %}
        <div class="blogs">
            <h3><a href="/blog/detail/{{ article_index.id }}/">{{ article_index.title }}</a></h3>
            <figure><a href="{{ article_index.url }}"> <img src="{{ MEDIA_URL }}{{ article_index.image }}" ></a></figure>
            <ul>

                <p>{{ article_index.content|slice:'150' }}</p>
              <a href="/blog/detail/{{ article_index.id }}/" target="_self" class="readmore">阅读全文&gt;&gt;</a>
            </ul>
            <p class="autor"><span>作者：{{ article_index.name.nick_name }}</span><span>分类：【<a href="/">{{ article_index.get_classify_display }}</a>】</span><span>浏览（<a href="#">{{ article_index.click_num }}</a>）</span></p>
            <div class="dateview">{{ article_index.add_time | center:'1'}}</div>
        </div>
        {% endfor %}


    </div>
    <div class="page">

            {% if articles_index.has_previous %}
                <a href="?{{ articles_index.previous_page_number.querystring }}">上</a>
            {% endif %}

            {% for page in articles_index.pages %}
                {% if page %}
                    {% ifequal page articles_index.number %}
                        <a href="?{{ page.querystring }}">{{ page }}</a>
                    {% else %}
                       <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    {% endifequal %}

                {% endif %}
            {% endfor %}
            {% if articles_index.has_next %}
                <a href="?{{ articles_index.next_page_number.querystring }}">下</a>
            {% endif %}



    </div>
  </article>
{% endblock %}
{% block right_coutent %}
      <aside>
    <div class="avatar"><a href="{% url 'users:user_info' %}" style="background: url('{{ MEDIA_URL }}{{ request.user.image }}') no-repeat; background-size: 160px 160px; "><span>修改资料</span></a></div>
    <div class="topspaceinfo">
      <h1>坚持最难，但成果也最大</h1>
      <p>不论你在什么时候开始，重要的是开始之后就不要停止....</p>
    </div>
    <div class="about_c">
      <p>网名：{{ request.user.nick_name }}</p>
      <p>职业：{{ request.user.profession }} </p>
      <p>籍贯：{{ request.user.address }}</p>
      <p>电话：{{ request.user.mobile }}</p>
      <p>邮箱：{{ request.user.email }}</p>
    </div>
   {% block news %}
    <div class="bdsharebuttonbox"><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a><a href="#" class="bds_more" data-cmd="more"></a></div>
    {% block right %}
    <div class="tj_news">

      <h2>
        <p class="tj_t1">最新文章</p>
      </h2>
      <ul>

          {% for article_new in article_news  %}
              <li><a href="/blog/detail/{{ article_new.id }}">{{ article_new }}</a></li>
          {% endfor %}


      </ul>
      <h2>
        <p class="tj_t2">推荐文章</p>
      </h2>
      <ul>

          {% for article_click in article_clicks  %}
                <li><a href="/blog/detail/{{ article_click.id }}/">{{ article_click.title }}</a></li>
          {% endfor %}

      </ul>
    </div>
     {% endblock %}
  {% endblock %}
    <div class="links">

    </div>

  </aside>
{% endblock %}

templates/my_blog/newlist.html
{% extends 'my_blog/base_blog.html' %}
{% load staticfiles %}
{% block coutent %}
     <article>
    <h2 class="about_h">您现在的位置是：<a href="/">首页</a>><a href="#">阅读人生</a></h2>
    <div class="bloglist">
    {% for read in all_read.object_list %}
      <div class="newblog">
        <ul>
          <h3><a href="{% url 'index:project_detail' read.id %}">{{ read.title }}</a></h3>
          <div class="autor"><span>作者：{{ read.author }}</span><span>分类：[<a href="/">{{ read.get_classify_display }}</a>]</span><span>浏览（<a href="/">{{ read.click_num }}</a>）</span></div>
          <p>{{ read.content|slice:'100' }}<a href="{% url 'index:project_detail' read.id %}" target="_self" class="readmore">全文</a></p>
        </ul>
        <figure><img src="{{ MEDIA_URL }}{{ read.image }}" ></figure>
        <div class="dateview">{{ read.add_time|slice:'1' }}</div>
      </div>

    {% endfor %}
    </div>
     <div class="page">

            {% if all_read.has_previous %}
                <a href="?{{ all_read.previous_page_number.querystring }}">上</a>
            {% endif %}

            {% for page in all_read.pages %}
                {% if page %}
                    {% ifequal page all_read.number %}
                        <a href="?{{ page.querystring }}">{{ page }}</a>
                    {% else %}
                       <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
                    {% endifequal %}

                {% endif %}
            {% endfor %}
            {% if all_read.has_next %}
                <a href="?{{ all_read.next_page_number.querystring }}">下</a>
            {% endif %}
        </div>
  </article>
{% endblock %}
{% block right_coutent %}
    <aside>
    <div class="rnav">
      <li class="rnav1 "><a href="?ct=">全部</a></li>
    <li class="rnav1 "><a href="?ct=rj">日记</a></li>
      <li class="rnav2 "><a href="?ct=xs">欣赏</a></li>
      <li class="rnav3 "><a href="?ct=cx">程序人生</a></li>
      <li class="rnav4 "><a href="?ct=jd">经典语录</a></li>
    </div>
    <div class="ph_news">
      <h2>
        <p>点击排行</p>
      </h2>
      <ul class="ph_n">
          {% for read in click_read %}
              <li><span class="num1">{{ forloop.counter }}</span><a href="{% url 'index:project_detail' read.id %}">{{ read.title }}</a></li>

          {% endfor %}

      </ul>
      <h2>
        <p>栏目推荐</p>
      </h2>
      <ul>
      {% for i in click_read %}
        <li><a href="#">{{ i.title }}</a></li>
        {% endfor %}
      </ul>

    </div>

  </aside>
{% endblock %}