LxMyblog/urls.py
# !/usr/bin/env python
# -*- coding:utf-8 -*-
"""LxMyblog URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Import the include() function: from django.conf.urls import url, include
    3. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve

from my_users.views import LoginView, RegisterView, LogoutView
from LxMyblog.settings import MEDIA_ROOT
from my_blog.views import IndexView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^$', IndexView.as_view(), name="index"),
    url(r'^blog/', include('my_blog.urls', namespace='index')),
    url(r'^users/', include('my_users.urls', namespace='users')),
    url(r'media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    # url(r'static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),


    # 登录
    url(r'^login/', LoginView.as_view(), name='login'),
    # 退出
    url(r'^logout/', LogoutView.as_view(), name='logout'),
    # 注册
    url(r'^register/', RegisterView.as_view(), name='register'),

]

my_blog/urls.py
# !/usr/bin/env python 
# -*- coding:utf-8 -*-
__author__ = '_X.xx_'
__date__ = '2018/6/21 22:10'

from django.conf.urls import url
from .views import AboutView, ArticleView, AddCommentsView, ProjectView, \
    ProjectDetailView, TemplateView

urlpatterns = [
    # 关于我页面
    url(r'^about$', AboutView.as_view(), name='about'),
    # 图片显示页
    url(r'^template$', TemplateView.as_view(), name='template'),
    # 点击阅读全文跳转页面
    url(r'^detail/(?P<article_id>\d+)/$', ArticleView.as_view(), name='detail'),
    # 添加文章评论
    url(r'^add_comment/(?P<article_id>\d+)$', AddCommentsView.as_view(),
        name="add_comment"),
    # 项目简介
    url(r'^project$', ProjectView.as_view(), name='project'),
    # 点击阅读全文跳转页面
    url(r'^project_detail/(?P<project_id>\d+)/$', ProjectDetailView.as_view(),
        name='project_detail'),

]

my_users/urls.py
# !/usr/bin/env python 
# -*- coding:utf-8 -*-
__author__ = '_X.xx_'
__date__ = '2018/6/21 23:07'

from django.conf.urls import url
from .views import UserInfoView, UploadImageView, UpdatePwdView, UserinfoView

urlpatterns = [
    # 用户个人资料页
    url(r'^info/$', UserInfoView.as_view(), name='user_info'),
    # 用户修改头像
    url(r'^image/up_load$', UploadImageView.as_view(), name='up_load'),
    # 用户修改密码
    url(r'^update/pwd/$', UpdatePwdView.as_view(), name='update_pwd'),
    # 用户修改资料
    url(r'^update/user_info/$', UserinfoView.as_view(), name='user_info'),
]

templates/usercenter-base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}个人信息- X.xx播客{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'css/lq.datetimepick.css' %}"/>
    {% block custom_css %}
    {% endblock %}


    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>

</head>
<body>

<section>
	<div class="wp list personal_list">
	<div class="left">
        <ul>
            {% if request.user.is_authenticated %}
                <li class="active2"><a href="{% url 'index' %}">回到首页</a></li>
            {% else %}
                <li class="active2"><a href="{% url 'login' %}">重新登录</a></li>
            {% endif %}

        </ul>
	</div>

    {% block right_content %}

    {% endblock %}

	</div>
</section>


<!--sidebar start-->

<!--sidebar end-->
<!--header start-->

<div class="dialog" id="jsDialog">
    <div class="successbox dialogbox" id="jsSuccessTips">
        <h1>成功提交</h1>
        <div class="close jsCloseDialog"><img src="../images/dig_close.png"/></div>
        <div class="cont">
            <h2>您的需求提交成功！</h2>
            <p></p>
        </div>
    </div>
    <!--提示弹出框-->
    <div class="bidtips dialogbox promptbox" id="jsComfirmDialig">
        <h1>确认提交</h1>
        <div class="close jsCloseDialog"><img src="../images/dig_close.png"/></div>
        <div class="cont">
            <h2>您确认提交吗？</h2>
            <dd class="autoTxtCount">
                <div class="button">
                    <input type="button" class="fl half-btn" value="确定" id="jsComfirmBtn"/>
                    <span class="fr half-btn jsCloseDialog">取消</span>
                </div>
            </dd>
        </div>
    </div>
    <div class="resetpwdbox dialogbox" id="jsResetDialog">
        <h1>修改密码</h1>
        <div class="close jsCloseDialog"><img src="../images/dig_close.png"/></div>
        <div class="cont">
            <form id="jsResetPwdForm" autocomplete="off">
                <div class="box">
                    <span class="word2" >新&nbsp;&nbsp;密&nbsp;&nbsp;码</span>
                    <input type="password" id="pwd" name="password1" placeholder="6-20位非中文字符"/>
                </div>
                <div class="box">
                    <span class="word2" >确定密码</span>
                    <input type="password" id="repwd" name="password2" placeholder="6-20位非中文字符"/>
                </div>
                <div class="error btns" id="jsResetPwdTips"></div>
                <div class="button">
                    <input id="jsResetPwdBtn" type="button" value="提交" />
                </div>
                {% csrf_token %}
            </form>
        </div>
    </div>

</div>
<div class="bg" id="dialogBg"></div>


<div class="bg" id="dialogBg"></div>


<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/validateDialog.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>

<script src='{% static 'js/plugins/jquery.upload.js' %}' type='text/javascript'></script>
<script src="{% static 'js/validate.js' %}" type="text/javascript"></script>



{% block custom_js %}
{% endblock %}

</body>
</html>

templates/usercenter-info.html
{% extends 'usercenter-base.html' %}
{% block title %}
    X.xx个人播客-修改资料
{% endblock %}
{% load staticfiles %}
{% block custom_js %}
    <script src="{% static 'js/deco-user.js' %}"></script>
{% endblock %}
{% block right_content %}
     <div class="right">
		<div class="personal_des ">
			<div class="head" style="border:1px solid #eaeaea;">
				<h1>个人信息</h1>
			</div>
			<div class="inforcon">
				<div class="left" style="width:242px;">
                    <iframe id='frameFile' name='frameFile' style='display: none;'></iframe>
                    <form class="clearfix" id="jsAvatarForm" enctype="multipart/form-data" autocomplete="off" method="post" action="{% url 'users:up_load' %}" target='frameFile'>
                        <label class="changearea" for="avatarUp">
                            <span id="avatardiv" class="pic">
                                <img width="100" height="100" class="js-img-show" id="avatarShow" src="{{ MEDIA_URL }}{{ request.user.image }}"/>
                            </span>
                            <span class="fl upload-inp-box" style="margin-left:70px;">
                                <span class="button btn-green btn-w100" id="jsAvatarBtn">修改头像</span>
                                <input type="file" name="image" id="avatarUp" class="js-img-up"/>
                            </span>
                        </label>
                        {% csrf_token %}
                    </form>
                    <div style="border-top:1px solid #eaeaea;margin-top:30px;">
                        <a class="button btn-green btn-w100" id="jsUserResetPwd" style="margin:80px auto;width:100px;">修改密码</a>
                    </div>
				</div>
				<form class="perinform"  autocomplete="off" method="post" action="{% url 'users:user_info' %}">
					<ul class="right">
						<li>昵&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;称：
                           <input type="text" name="nick_name" id="nick_name" value="{{ request.user.nick_name|default_if_none:'' }}" maxlength="10">
                            <i class="error-tips">{{ user_info_form.errors}}</i>
                        </li>
						<li>职&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;业：
                           <input type="text"  id="profession" name="profession" value="{{ request.user.profession|default_if_none:'' }}" />
                            <i class="error-tips">{{ user_info_form.errors }}</i>
						</li>
						<li>性&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;别：
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio"  name="gender" value="male" {% if request.user.gender == 'male' %} checked="checked"{% endif %} >男</label>
							<label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="radio" name="gender" value="female" {% if request.user.gender == 'female' %} checked="checked"{% endif %}>女</label>
						</li>
						<li class="p_infor_city">地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址：
                            <input type="text" name="address" id="address" placeholder="请输入你的地址" value="{{ request.user.address|default_if_none:'' }}" maxlength="10">
						    <i class="error-tips"></i>
                        </li>
						<li>手&nbsp;&nbsp;机&nbsp;&nbsp;号：
                            <input type="text" name="mobile" id="mobile" placeholder="请输入你的手机号码" value="{{ request.user.mobile|default_if_none:'' }}" maxlength="10">
                            {{ user_info_form.errors }}
                        </li>
                        <li>邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：
                        	<input class="borderno" type="text" name="email" readonly="readonly" value="{{ request.user.email|default_if_none:'' }}"/>
                            <span class="green changeemai_btn"></span>
                    	</li>
						<li class="button heibtn">
							<input type="submit"  value="保存">

						</li>
                      <p style="color:#e41635;">{{ msg }}</p>
					</ul>

                    {% csrf_token %}
				</form>

			</div>
		</div>
	</div>
{% endblock %}